package com.bergama.tarih;

import android.os.Bundle;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.viewpager.widget.ViewPager;

import java.util.ArrayList;

public class SlideActivity extends AppCompatActivity {
    private ArrayList<PageModel> modelArrayList;
    private ViewPager viewPager;
    private Adapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_slide);

        viewPager = findViewById(R.id.view_pager);
        loadcards();

        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                // ai seslendirme burda ayarlanacak
            }

            @Override
            public void onPageSelected(int position) {

            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });

    }
    private void loadcards() {
        modelArrayList = new ArrayList<PageModel>();

        int slide = getIntent().getIntExtra("slide", 0);
        switch (slide) {
            case 0: //test
                modelArrayList.add(new PageModel("Test amaçlıdır", "Açıklama 1", R.drawable.github));
                modelArrayList.add(new PageModel("Bazilika", "Açıklama 2", R.drawable.bazilika2));
                modelArrayList.add(new PageModel("Baedesten", "Açıklama 3", R.drawable.bedesten));
                break;
            case 1: // Genel
                modelArrayList.add(new PageModel("Bergama Adı Nereden Geliyor?", "Helenlerden çok önce Batı Anadolu'da Pelasglar ve Luvi halkı yaşardı. Bergama'nın ilk adı Parg-a-uma idi. Arapçada Perg \"kale\", Uma “halk” demektir. Pergamon adı ise, Helenleşmenin başlamasıyla dönüşen bir kelimedir. Sonradan da dönüşerek Bergama oldu.", R.drawable.bergama1));
                modelArrayList.add(new PageModel("Bergama Kağıdı", "Deriye yazı yazmayı bulan Bergama Krallığı papirüsten sonra daha kullanışlı bir kâğıt buldu, buna \"Bergama Kâğıdı\" anlamına gelen \"Parşömen\" adını verdiler.", R.drawable.bergama2));
                modelArrayList.add(new PageModel("Gezilmesi Gereken Bir Yer", "Bergama sahip olduğu, zengin tarihi ve kültürel değerleriyle insanlığın çok değerli hazinelerindendir. İlçe merkez ve çevresinde Arkaik, Helenistik, Roma, Bizans, Selçuklu ve Osmanlı devirlerine ait önemli ziyaret yerleri vardır. Bergama denildiği zaman, öncelikle Akropol, Asklepeion, Kızıl Avlu, Kleopatra Güzellik Ilıcası ve Kozak Yaylası akla gelir." ,R.drawable.akropol1));
                modelArrayList.add(new PageModel("Turizm", "Bergama Antik Çağ’dan beri pek çok uygarlığa ev sahipliği yapmış, pek çok tarihi ve kültürel değere sahip bir yerleşimdir. Türkiye’nin ilk arkeoloji müzesi olan Bergama Müzesi, günümüzde en çok bilinen ve ziyaret edilen müzeler arasındadır. UNESCO süreci ve Dünya Kültür Mirası listesine alınmasıyla birlikte Bergama’ya gelen turist sayısında ve turistlerin kalış süresinde artışlar olmaktadır.", R.drawable.bergama3));
                modelArrayList.add(new PageModel("Şifalı Su", "Bergama tarihi, kültürel değerler mozaiğinin yanında zengin doğal güzelliklere de sahiptir.Bergama antik dönemde de, bugün olduğu gibi, yoğun trafiğin biraz dışında konumlanmıştı. Kuzeyde Pindasos ( Kozak Dağı), güneyinde Aspordenon ( Yünd Dağı) yer alır. Yünd Dağı volkanik bir dağ olduğu için, bölgede tüf ve sıcak su kaynakları oldukça yoğundur. Bergama Asklepionu'nda bu sular pek çok kişinin tedavi edilmesinde kullanılmıştır.", R.drawable.bergama4));
                modelArrayList.add(new PageModel("Kuruluş", "Bergama, Kaikos (Bakır Çay) nehri kenarında kurulmuştur. Doğu Ege dağlık alanı içinde kalan bölge, batıdaki kıyı şeridi ve doğudaki Anadolu yükseltisi arasında geçitlerin olduğu bir noktadadır. Bölgedeki nehirlerin ağızlarında  önemli liman kentleri kurulmuştur.", R.drawable.bergama5));
                modelArrayList.add(new PageModel("İklim" ,"Bölgede Akdeniz iklimi hakimdir. Çam ve meşe doğal bitki örtüsünü oluşturur. 400 metre yüksekliğe kadar zeytin ağaçları mevcuttur.", R.drawable.bergama6));
                modelArrayList.add(new PageModel("Efsane", "Kent “Telephos Efsanesi’nde geçmektedir. Efsaneye göre, Arkadia bölgesindeki Tegea kralı Aleos’a bir kahin, kızı Augea’den doğacak erkek bir çocuğun, dayılarını, yanı kralın oğullarını öldüreceğini bildirir. Olympia’ya gitmekte olan Herakles Augea ile karşılaşmış ve onu hamile bırakmıştır. Augea bir süre sonra Telephos’u doğurunca babası kahinin söylediklerini hatırlar, bebeği Parthenion Dağı’na, kızı Augea’yı da sandık içinde denize bırakır. Augea’nin içinde bulunduğu sandık, Mysia kıyılarına çıkmış ve Mysia kralı Teutras kızı evlat edinmiştir.", R.drawable.bergama7));
                modelArrayList.add(new PageModel("Efsane", "Oğlu Telephos’u arayan Herakles onu, Parthenion Dağ’ında, bir ceylan tarafından emzirilirken bulur ve Kral Karithos’un yetiştirmesi için yanına bırakır. Telephos büyümüş ve Anadolu’ya annesini aramaya gitmiştir.O sırada Mysia kralı Teutras savaş halindedir ve güç durumdadır.Telephos krala yardım etmiş ve bundan çok memnun olan kral da onu manevi kızı Augea ile evlendirmeye karar vermiştir. Düğün gecesi Augea ve Telephos, birbirlerini tanımış ve ana oğul olduklarını anlamışlardır. Kralın ölümünden sonra Telephos onun yerine geçmiş ve Parg-a-uma şehrini kurmuştur.", R.drawable.bergama8));
                modelArrayList.add(new PageModel("Pergamon ve Persler", "Kent, M.Ö. 399 yılında Yunanistan’a yürüyen Xenophon komutasındaki Perslilere kapılarını açmıştır. Dönemin Pergamon yöneticisi, Gongylos adındaki yerel bir kralın dul eşi Hellas’dır. Gongylidler yüz yıl kadar önce Euboia’dan, Persler tarafından getirilip bölgeye yerleştirilmiş, Perslere bağlı, fakat kısmi özgürlüklere sahip bir hanedan olmuşlardır.", R.drawable.bergama9));
                modelArrayList.add(new PageModel("Asklepion Kültürü", "M.Ö. 4. yüzyılda Asklepion kültünün kente gelmesi önemli bir ayrıntıdır. Şehir, Asklepion Tapınağı ile ünlenir. M.Ö. 334 yılında Pergamon’un kuzeyindeki Granikos’da Aleksandros’un Persleri yenmesinden sonra şehir onun egemenliğine girer. Aleksandros, kentin ölen Persli yöneticisinin dul eşi, Prenses Barsine’yi kentin yöneticisi yapar ve ondan Herakles adını verdiği bir oğlu olur. Prenses ve oğlu, M.Ö. 4. yüzyılın üçüncü çeyreğinde, çok korunaklı bir kale olan Pergamon’da yaşarlar ve Aleksandros’un ölümünden sonra bu oğul, varisi olarak bir rol oynamıştır. Barsine, M.Ö. 4. yüzyıla tarihlenen Athena Tapınağı’nın finansörüdür. M.Ö. 3. yüzyıl’da Pergamon, korunaklı, varsıl, gelişen ve yerelin dışında da önemli bir kent olmuştur.", R.drawable.asklepion1));

                break;
            case 2:
                modelArrayList.add(new PageModel("Akropol", "II. Eumenes devrinin en önemli yapıları arasında Galatların mağlup edilmesi anısına inşa edilen Zeus Sunağı, Athena Tapınağı’nın propylonu ve onu çevreleyen stoaları; 200.000 kitap rulosunun muhafaza edildiği ünlü kütüphane, büyük saray ve kent surları yer alır. Bu gelişme dönemi sırasında daha önce inşa edilmiş olan Athena Tapınağı ile on bin seyirci kapasiteli antik çağın en dik tiyatrosu korunmuş, kent bu çekirdeğin üç bir tarafında yelpaze biçiminde açılan bir plan düzeni içerisinde gelişmiştir.", R.drawable.akropol1));
                modelArrayList.add(new PageModel("Yukarı Kent", "Yukarı şehir daha çok kral aileleri ile ileri gelenlerin, aydınların, komutanların ikamet ettiği bir merkezdeydi. Bu nedenle burasının resmi bir karakteri vardır.Kentin orta kesiminde kuzeyden güneye doğru Hera ve Demeter kutsal alanları, Asklepios Tapınağı, Gymnasionlar ve kent çeşmesi yer almaktaydı. Bu yönü ile orta kentte, yönetim ile doğrudan ilgili olmayan yapılarla, halkın rahatlıkla girip çıktığı toplantı yerleri bulunmaktaydı.", R.drawable.akropol2));
                modelArrayList.add(new PageModel("Aşağı Kent", "Aşağı kentte Aşağı Agora, orta ve yukarı şehre çıkan ana yolun iki yanında sınırlanan çok sayıda dükkân, Attalos evi olarak adlandırılan peristylli evler yer alır. Yukarı şehirdeki agora, mevki ve konum olarak yüksekte yer alıyordu. Dolayısıyla aşağı agora kentin ticaret merkezi olarak yer almaktaydı", R.drawable.akropol3));
                break;
            case 3:
                modelArrayList.add(new PageModel("Asklepion", "Bergama Asklepion’u Eskiçağ’da önemli bir sağlık tedavi merkezi idi. Pausanias’a göre Bergama’da ilk Asklepios Tapınağı M.Ö. 4. yüzyılın ilk yarısında kurulmuştu. Kazılarda kutsal yerin M.Ö. 4. yüzyıldan beri var olduğu ve Hellenistik Dönemde geliştiği saptanmıştır. Asklepios Kutsal Alanı, galerili avlusu, 3500 kişilik tiyatro yapısı, İmparator Hadrianus’a ait kült salonu, kütüphanesi, yuvarlak planlı Asklepios Tapınağı ile Roma Dönemi’nde oldukça önemli bir sağlık merkeziydi.", R.drawable.asklepion1));
                modelArrayList.add(new PageModel("Kutsal Kaynaklar", "Güney kesiminde Hellenistik Dönemden kalma üç küçük tapınak ile uyku odaları, kutsal kaynak ve havuzlar bulunmaktadır. Kutsal kaynak yanında burada tedavi gören hastaların soğuk ve sıcak havadan korunmasını sağlamak amacıyla uzun bir yer altı tüneli yapılmıştır.", R.drawable.bergama4));
                modelArrayList.add(new PageModel("Asklepios Tapınağı", "Bu yer altı tünelinin hemen kuzeyinde yuvarlak planlı Asklepios Tapınağı yer alır. Bu tapınak Roma’daki Pantheon örnek alınarak M.S. 150 yıllarında Konsül L.C Rufinus tarafından yaptırılmıştır. Burada genellikle telkin ve fizik tedavinin bugün halen kullanılmakta olan çeşitli şekilleri uygulanmaktaydı. Kutsal sudan içilmesi, su-çamur banyoları, açlık-susuzluk kürleri, şifalı otlar, kremlerle yağlanma başlıca tedavi yöntemleriydi", R.drawable.asklepion2));
                break;
            case 4:
                modelArrayList.add(new PageModel("Allianoi", "Allianoi, \"Sağlık Tanrısı Asklepois\"in yurdu olarak biliniyor. ASKLEPIOS Antik Grek mitolojisinde hasta insanlara şifa dağıtan, hekimliğin ve tıp biliminin tanrısıydı. Apolion oğlu Asklepiosu yarı at yarı insan olan Khiron'a emanet etti. Khiron ona okuma, yazma ve önemli hastalıkların tedavisinde kullanılan ilaçların formüllerini öğretti. Asklepios’un ünü kısa sürede yayıldı. Asklepios ölüleri de diriltiyordu. Zeus buna kızdığı için Asklepiosu öldürttü. Yunanlılar Asklepiosun adını yaşatmak amacı ile aynı isimle sağlık merkezleri yaptılar. Allianoi de bunlardan birisidir.", R.drawable.allianoi1));
                modelArrayList.add(new PageModel("Allianoi", "Topraklarından 45 derece kükürtlü su çıkan şifa merkezi Allianoi, bu özelliğiyle dünyanın dört büyük sağlık merkezinden birisidir. Pergamon Krallığı'nın sayfiye yeri olan bölge, yıllarca Hydroterapi (suyla tedavi) merkezi olarak hizmet vermiş. Yortantı Barajı’nın yapım aşamasında antik değeri anlaşılan bölgede, hızlandırılan kazı çalışmaları esnasında, bölgenin Helenistik Çağ'da kurulduğu ve en parlak dönemini Roma İmparatorluğu Hadrian'la yaşadığı ortaya konulmuştur. Bu kazı çalışmaları sayesinde, kentin sağlık merkezi Asklepionlar'dan biri olduğu anlaşılmış.", R.drawable.allianoi2));
                modelArrayList.add(new PageModel("Allianoi", "Kazılar sayesinde Bergama, arkeoloji alanında bölgenin ve Türkiye'nin önemini daha da artıran Asklepieion kültürünün Anadolu'da yaygın olduğunu da kanıtlandı. Bergama'nın yaklaşık 23 kilometre doğusunda Bergama-İvrindi karayolunun üzerinde yapılan kazı çalışmalarıyla ortaya çıkarılan Allianoi antik yerleşmesi M.Ö. 1. yüzyılda Paşa Ilıcası ve çevresinde kurulmuştur. 1998–99 yılı kazıları sonucunda Helenistik Çağ, mimari, buluntularının yanı sıra özellikle M.S. 2.yüzyıla ait pek çok arkeolojik eser ele geçirildi.", R.drawable.allianoi3));
                modelArrayList.add(new PageModel("Allianoi", "Ayrıca kazılarda; çok sayıda heykeltıraşlık eser, metal eserler, çanak çömlek, kandiller, kemik objeler, çok sayıda üzeri işlemeli cam eser, 1500 civarında altın, gümüş ve bronz sikke, en son olarak da 2. yüzyıl Roma döneminden kalma mermer Afrodit heykeli bulundu. Bugüne kadar kazıda çıkan önemli eserler arasında Afrodit heykeli, iki Asklepios başı, torsolar, termal havuzlar, heykeltıraşlık parçalar, dükkânlar, çeşme, şarap imalathanesi, seramik fırınları, antik kaideler bulunmaktadır.", R.drawable.allianoi4));
                break;
            case 5:
                modelArrayList.add(new PageModel("Bazilika", "Binanın tamamının tuğladan yapılmış olması ve büyük ön avlusu sebebi ile tapınak halk arasında “Kızıl Avlu” olarak adlandırılmıştır. Avlusu yüksek duvarlarla dışarıya kapalı idi. Mısır Tanrılarına verilen önem sebebi ile tapınak Roma Dönemi aşağı Bergama kentinin tam merkezine inşa edilmiştir. Tapınağın avlusu ile bütünleşmesine engel teşkil eden Selinos çayında, bugün halen kullanılmakta olan su tünelleri inşa edilmiştir.", R.drawable.bazilika1));
                modelArrayList.add(new PageModel("Bazilika", "Kült ve sanat tarihi verilerine dayanarak tapınağın M.S. ikinci yüzyılda, muhtemelen İmparator Hadrian döneminde inşa edildiği ve Mısır tanrıları hem Serapis hem İsis’e ithaf edildiği söylenebilir. Ancak tapınağın iki yanındaki yuvarlak yapıda kült mihraplarının bulunmasına karşılık tanrıların kimler olduğu bilinmemektedir. Erken Bizans döneminde kutsal mekânın içine ilaveler yapılan tapınak Anadolu’daki erken yedi kiliseden biri olarak kullanılmaya devam etmiştir.", R.drawable.bazilika2));
                modelArrayList.add(new PageModel("Ulu Camii", "1399 yılında Yıldırım Beyazıt tarafından yaptırılan tek minareli Selahattin camilerindendir. Orta nefi 3 kubbeli, iki yan nefi tonozla örtülüdür. Doğu cephesinde iki pencereden daraltılan duvar içinde kurşunluğa çıkan merdivenler vardır. Mermer mihrabı Selçuk etkilerini taşır. Minberi, tas ve mermerden yapılmış kitabeli tas kapısı özenli bir işçiliğe sahiptir.", R.drawable.ulucamii));
                modelArrayList.add(new PageModel("Çukurhan", "İnşa tarzına göre, hanın XIV-XV. yüzyıllarında yapıldığı tahmin olunmaktadır. Burada, üstü tonozlu bir çarşının da bulunduğu kalan izlerden anlaşılmaktadır.", R.drawable.cukurhan));
                modelArrayList.add(new PageModel("Taşhan", "1432 yılında inşa edilen handa devşirme malzeme bol miktarda kullanılmıştır. Cephesinde antik taşların kullanıldığı yapının üst katları tuğla-tas almaşık örgüye sahip idi. Yapı harap durumdadır.", R.drawable.tashan));
                modelArrayList.add(new PageModel("Küplü Hamam", "1427 yılında yapılan hamamın kadınlar bölümü yoktur. Taç kapısı, kirpi saçakları ve ilginç kubbe süslemeleriyle literatüre geçmiştir. 19. yüzyıla kadar korunan ve bugün Paris Louvre Müzesinde bulunan antik mermer küp nedeniyle Küplühamam adıyla bilinmektedir.", R.drawable.kuplu_hamam));
                modelArrayList.add(new PageModel("Kurşunlu Camii", "Hükümet Konağı yanındadır. Kubbesi kurşun kaplı olduğundan bu adı almıştır. Doğuya bakan duvarındaki iki satır kitabesine göre, bu cami, Safi’nin oğlu Hacı Hasan tarafından 873(1439) yılında yaptırılmıştır.Cami, muhtelif zamanlarda çeşitli tamir görmüştür. Birçok yerleri, tamir ve temizlik sıva ve badana ile örtülmüştür. Bu yüzden binanın asaletini gösteren taşlar kapatılmış bulunmaktadır. Caddeye bakan duvardaki Maşallah yazılı levha, 1301(1885) yılında konmuştur.Burada bulunan yılan kabartmalı bir taş sökülerek İzmir’e götürülmüş, orada kayığa konurken denize düşürülmüştür.Cami Avlusu 30 yıl önceye kadar mezarlıktı. Burada Karaosmanoğulları sülalesine ait mezarlar da bulunuyordu.", R.drawable.kursunlu_camii));
                modelArrayList.add(new PageModel("Tabaklar Hamamı", "Eskiden çay boyunda bulunan tabakhaneler arasında kaldığından bu adı almıştır. Daha eskiden ise, bu civarda Pabuççular arastası (Başmak Pazarı) bulunduğundan bu isimle anılmıştır. Buraya Çınarlı Çarşı da denilmiştir.Hamam, 1258(1842) senesindeki sel baskınında harap olmuştur. Hamam, tezyinatının zenginliği ve çeşitliliği itibariyle sanat bakımından üstün bir değer taşımaktadır.Bugün tamamıyla sökülmüş olan döşemenin altındaki cehennem yollarıyla hamamın ısıtıldığı izlerden belli olmaktadır.", R.drawable.tabaklar_hamami));
                modelArrayList.add(new PageModel("Bedesten", "Eskiden burada çeşitli eşya satıldığı için bu adı muhafaza etmiştir.Yapı tarzına göre XVI-XVII. yüzyıl arasında yapılmış olduğu anlaşılmaktadır.", R.drawable.bedesten));
                modelArrayList.add(new PageModel("Hacı Hekim Hamamı", "Erkek ve kadınlar için iki bölüme ayrıldığından Çifte Hamamlar veya Çarşı Hamamı denilir. Kapısı üstündeki boşlukta kitabesinin bulunduğu sanılmaktadır. 1336(1918) tarihli berat bu hamamın Hacı Hâkim Camisi’ne vakfedildiğini yazmaktadır.", R.drawable.haci_hekim_hamami));
                break;
            case 6:
                modelArrayList.add(new PageModel("Çok Katmanlı Kültürel Peyzaj Alanı", "Helenistik, Roma, Doğu Roma ve Osmanlı Dönemlerine ait katmanları içerisinde barındıran Bergama, Çok Katmanlı Kültürel Peyzaj Alanı; Pergamon, Kibele Kutsal Alanı, İlyas Tepe, Yığma Tepe, İkili, Tavşan Tepe, X Tepe, A Tepe ve Maltepe Tümülüsleri olmak üzere toplam 9 bileşenden oluşmaktadır. UNESCO Dünya Mirası Listesi'ne 999. sıradan girmiştir.", R.drawable.unesco));
                modelArrayList.add(new PageModel("Mimari", "Kale Dağı’nın tepesindeki antik Pergamon yerleşimi, anıtsal mimarisiyle Helenistik dönem şehir planlamacılığının en iyi örneklerinden birini temsil eder. Athena Tapınağı, Trajan Tapınağı, Helenistik dönemin en dik tiyatro yapısı, kütüphane, Heroon, Zeus Sunağı, Dionysos Tapınağı, Agora ve Gymnasion yapıları; bu planlama sisteminin ve döneme özgü mimarinin seçkin örnekleri olarak dikkat çeker.", R.drawable.asklepion1));
                modelArrayList.add(new PageModel("Somut Olmayan Kültürel Miras", "Bergama; Uluslararası Bergama Kermesi, Çeyiz ve Çeyiz Serme, Sünnet Yatağı, Karatabakçılık, Sepet Yapımı, Telkırma ve Klarnet Çalma gelenekleriyle Somut Olmayan Kültür Mirası Ulusal Envanteri'nde yer almaktadır.", R.drawable.bergama_kermesi));
                break;
            case 7:
                modelArrayList.add(new PageModel("Kuruluş", "Pergamon, ilk olarak M.Ö. 7–6. yüzyıllarda Akropol olarak bilinen Kale Dağı tepesinde kurulmuştur. Efsanelere göre şehri, Truva kahramanı Andromakhe’nin oğlu Pergamos ya da Herakles’in oğlu Telephos kurmuştur. Ancak arkeolojik bulgular, yerleşimin Eski Tunç Çağı’na (M.Ö. 3000) kadar uzandığını göstermektedir. Zamanla Pergamon, stratejik konumu ve savunulabilir yapısıyla büyümüş, Helenistik dönemde büyük bir kültür ve yönetim merkezi hâline gelmiştir", R.drawable.bergama1));
                modelArrayList.add(new PageModel("Kuruluş", "Pergamon antik kenti, Hellenistik dönemde Attalos soyunun yönettiği güçlü bir krallığa dönüşmüştür. Bu dönemde Bergama, coğrafi konumu ve Yunan kültürüne verdiği önemle Anadolu’nun önemli merkezlerinden biri haline gelmiş, Roma İmparatorluğu ile yakın ilişkiler kurarak Küçük Asya’nın siyasal dengesinde önemli rol oynamıştır. Attalid hanedanının her hükümdarı (Philetairos’tan Attalos III’e kadar) kent ve krallık için ayrıcalıklı politikalar geliştirmiştir. Aşağıda her bir kralın dönemi, önemli olaylar, kültürel gelişmeler, yapılar ve dış ilişkiler bağlamında incelenmiştir", R.drawable.akropol1));
                modelArrayList.add(new PageModel("Philetairos (M.Ö. 282–263)", "Philetairos, Bergama’nın ilk bağımsız hükümdarı ve Attalos soyunun kurucusudur. Başlangıçta Trakya Kralı Lysimakhos’un veziri olarak Pergamon kalesine ve hazinesine bakıyordu; Lysimakhos’un M.Ö. 281’de yenilgiye uğraması sonrası Seleukos I Nikator yanına geçerek ona bağlılığını bildirmiş ve bu sayede Bergama’da büyük bir özerklik elde etmiştir. Philetairos’un politikaları, Pergamon’u “doğuda Yunan uygarlığının önde gelen bir merkezi” yapma yolunda temel oluşturmuştur. Dönemi boyunca Delphi ve Delos tapınaklarına yaptığı büyük bağışlarla ailesinin prestijini artırdı; böylece dış dünyada Bergama’nın nüfuzu yükseldi.", R.drawable.tarih1));
                modelArrayList.add(new PageModel("Philetairos (M.Ö. 282–263)", "Mimari açıdan Philetairos önemli eserler yaptırdı. Akropol’de günümüze kalıntıları ulaşan Athena Tapınağı, muhtemelen onun döneminde inşa edilmiştir. Ayrıca, tanrıça Demeter’e adanmış kutsal alandaki tapınak ve sunağın yapımına Philetairos ile kardeşi Eumenes ve anneleri Boa katkıda bulunmuştur. Bu erken yapılar ilerideki büyük kentleşme hamleleri için temel oluşturmuştur. Philetairos, vasiyetinde yeğeni Eumenes’i (I. Eumenes) varis tayin etti; böylece Bergama yönetimi Eumenes’in eline geçti. Sonuç olarak Philetairos, Pergamon’u küçük bir kale iken güçlü bir krallığın çekirdeği haline getiren temelleri atmıştır.", R.drawable.tarih2));
                modelArrayList.add(new PageModel("I. Eumenes (M.Ö. 263–241)", "Eumenes I, Philetairos’un yeğeni ve halefi olarak 263’te tahta geçmiştir. 263–241 döneminde hüküm süren Eumenes, M.Ö. 262 yılında Seleukos Kralı II. Antiochos’u Sardes yakınlarında yenerek Pergamon’un Süleukos hâkimiyetinden kurtulmasını sağlamıştır. Bu zaferle Pergamon’un toprakları önemli ölçüde genişlemiş; kuzeyde Philetaireia, doğuda Attaleia adıyla yeni garnizon yerleşimleri kurarak sınırlarını Akdeniz’e kadar uzatmıştır. Yüzde Selçuklu egemenliğini göstermek için üzerindeki portreyi Seleukos yerine önceki hükümdar Philetairos olarak değiştirdi.", R.drawable.tarih3));
                modelArrayList.add(new PageModel("I. Eumenes (M.Ö. 263–241)", "Dış ilişkilerde Eumenes I, II. Ptolemaios’un teşvikiyle Seleukoslara isyan ederken, II. Antiokhos Theos ile dostça ilişkiler kurdu ve İkinci Suriye Savaşı’nda Mısırlılarla müttefik oldu. Galatlara (Kelt Trakları) verilen vergiyi ödemeyi sürdürerek doğrudan çatışmadan kaçındı. Kendi döneminde Bergama’da büyük anıtsal yapılar yerine savunma tesisleri güçlendirildi; ancak hükümdarlığı niteliksel olarak bağımsızlığın pekiştiği bir dönem olarak önem kazandı. Eumenes I’in ölümü üzerine oğlu olmadığından Attalus (sonradan I. Attalos) isminde yeğenine mirası devretti. Bu dönemde Bergama, kendini Seleukos hâkimiyetinden kurtaran bir şehir-devlet olarak Batı Anadolu politikasında bağımsız bir aktör haline gelmiştir", R.drawable.tarih4));
                modelArrayList.add(new PageModel("I. Attalos (M.Ö. 241–197)", "Attalos I Soter, Eumenes I’in evlatlık oğlu ve ilk kez “kral” unvanını kullanan Attalid hükümdarıdır. Saltanatının başlarında (yaklaşık M.Ö. 238) Galatlardan (Anadolu’daki Kelt kabileleri) alınan vergiyi reddederek onlarla savaştı; Pergamon önlerinde Celti istilacılarını bozguna uğrattı. Bu zafer üzerine “Soter” (Kurtarıcı) lakabını aldı ve kendisini bağımsız bir krallık olarak ilan etti. Zaferinin anısına Pergamon’da “Ölü Galat” heykeliyle temsil edilen büyük bir kahramanlık grubu dikildi.", R.drawable.tarih5));
                modelArrayList.add(new PageModel("I. Attalos (M.Ö. 241–197)", "Dış politikada I. Attalos, baştan beri Roma ile yakın ittifak kurdu. Birinci ve İkinci Makedonya Savaşları’nda (M.Ö. 214–205 ve 200–196) Roma’nın yanında yer alarak Yunanistan’daki mücadeleleri destekledi. Bu savaşlarda Pergamon’a Aegina ve Andros gibi Ege adalarını kazandırdı. Aynı zamanda seleukoslarla da çatışarak II. Antiokhos Hierax’ı birkaç savaşta mağlup etti ve kısa süreliğine Anadolu’nun çoğuna hâkim oldu. Attalos I, “Yunan şehirlerinin özgürlüğünü barbarlara karşı savunan lider” kimliğini benimsedi; bu imajla Yunan dünyasında itibar kazandı. Kültürel katkı olarak kentte ve müttefik şehirlerde sanat ve anıtlara büyük destek verdi. Pergamon Akropolü’ne zafer anıtları, stoalar ve tapınaklar dikilmesine ön ayak oldu.", R.drawable.tarih6));
                modelArrayList.add(new PageModel("I. Attalos (M.Ö. 241–197)", "I. Attalos’un dönemi, Bergama’nın askeri ve diplomatik bakımdan güçlendiği, Roma tarafından güvenilen bir müttefik olarak konumlandığı; aynı zamanda kentte Helen kültürünün ve sanatının desteklendiği bir dönem olmuştur.", R.drawable.tarih7));
                modelArrayList.add(new PageModel("II. Eumenes (M.Ö. 197–159)", "II. Eumenes (Eumenes II Soter), I. Attalos’un oğlu ve Pergamon’un en parlak dönemini yaşatan hükümdardır. Saltanatının başlarında Roma ile ittifak halinde yer aldığı Romalı–Seleukos Savaşları’nda (M.Ö. 192–188) kilit rol oynadı. M.Ö. 190’da Magnesia Savaşı’nda Antiochos III’ü Romalı müttefikleriyle birlikte mağlup etti. Bu zaferin ardından M.Ö. 188’de imzalanan Apameia Antlaşması’yla Phrygia, Lydia, Pisidia, Pamphylia ve Likya’nın büyük kısmı Roma tarafından Pergamon’a bağışlandı. Böylece Pergamon’un sınırları tarihteki en geniş hâlini aldı. Ayrıca II. Eumenes, M.Ö. 168’deki Üçüncü Makedonya Savaşı’nda (Pydna Savaşı) Roma’yla birlikte hareket etti; ancak bu sırada Pers Kralı I. Perseus ile gizli temas kurmakla suçlanarak Roma’nın gözünde itibar kaybetti.", R.drawable.tarih8));
                modelArrayList.add(new PageModel("II. Eumenes (M.Ö. 197–159)", "Kültürel alanda II. Eumenes’in katkıları muazzamdır. Pergamon Akropolü’ndeki ünlü Zeus Sunağı onun döneminde inşa edilmiştir; sunağın muhteşem devfrizinde Gigantomakhos sahneleri betimlenir. Ayrıca krallık kütüphanesini büyük ölçüde genişleterek (yaklaşık 200.000 rulo içeren) dönemin en büyük ikinci kütüphanesi hâline getirdi. Crates of Mallos gibi bilim insanları krallığın koruması altına alındı ve Pergamon entelektüel bir merkez haline geldi. II. Eumenes zamanında Pergamon’a tiyatrolar, gymnasionlar ve tapınaklar inşa edildi, kütüphane ve saray kompleksleri yükseldi. Apameia’dan sonra kenti çevreleyen duvarlar da yenilenip dört kilometreye çıkarıldı; böylece Pergamon yaklaşık 90 hektarlık bir alana ulaştı. Attalid hükümdarları bergama’yı “ikinci bir Atina” yapma hedefiyle büyük bir kültür-sanat merkezi olarak geliştirmiştir.", R.drawable.tarih9));
                modelArrayList.add(new PageModel("II. Eumenes (M.Ö. 197–159)", "Dış ilişkilerde II. Eumenes, Roma’ya son derece yakın bir tutum sergiledi. II. Filipos’a karşı Romalılarla savaşarak ilişkilerini güçlendirdi; ancak M.Ö. 170’lerde Perseus’la temas iddiaları yüzünden ayrı düştü. Komşu krallıklarla ilişkisinde Bithynia’da Prusias I ile savaş (M.Ö. 183) göze çarpar; yenilmesine rağmen Roma müdahalesiyle sonuca gitmiştir. Genel olarak II. Eumenes dönemi Pergamon’un en büyük coğrafi genişliğe ulaştığı ve Helenistik kültürün zirve yaptığı bir dönem olarak kayda geçmiştir.", R.drawable.tarih10));
                modelArrayList.add(new PageModel("II. Attalos (M.Ö. 159–138)", "II. Attalos Philadelphos, II. Eumenes’in kardeşi ve saltanatının başında naip olarak görev yapan hükümdardır. Saltanat boyunca kardeşine sadakati ve diplomatik becerisiyle tanındı. Daha tahta çıkmadan önce bile M.Ö. 190’da Roma'ya II. Antiochos karşısında uyarı mektupları iletmiş, Magnesia Savaşı’nda orduyla birlikte yer almıştır. Pergamon Kralı olarak döneminde Pontus Kralı I. Pharnakes’e (M.Ö. 182–179) savaş açıp topraklarını genişletti. 172’de ağabeyi ölünce kendini krallığa layık görüp kraliçe Stratonike ile evlendi; ancak Eumenes’in sağ döndüğü anlaşılınca güç zevkini bırakıp tahttan çekildi.", R.drawable.tarih11));
                modelArrayList.add(new PageModel("II. Attalos (M.Ö. 159–138)", "Kısmen naip, kısmen kral olarak II. Attalos, bölgesel politikalarda aktif oldu. Roma’nın desteğiyle Bitinya Kralı II. Prusias’ı (M.Ö. 156–154) yenmesinin yanı sıra, 152’de Seleukos taht mücadelelerinde Aleksander Balas’ı, 149’da ise Bitinya tahtında Prusias’ın yerine oğlu Nikomedes II’yi iktidara taşıdı. Bu hamleler Anadolu’daki jeopolitik dengeyi Pergamon lehine şekillendirdi. Eyalet ilişkilerinde ise Pergamon’un müttefiki olarak kabul ettiği Roma ile iletişimi hep güçlü tuttu; Roma Senatosu onun krallığını bir süre bile sorguladıysa da II. Attalos itibarını korudu.", R.drawable.tarih12));
                modelArrayList.add(new PageModel("II. Attalos (M.Ö. 159–138)", "Kültür ve şehirleşmede II. Attalos dönemi, yeni kent kurma projeleriyle dikkat çeker. Pergamon dışına çıkarak Pamfilya’da (bugünkü Antalya) Attalia, Lydia’da Philadelphia adında yeni kentler kurdurdu. Sanat ve bilimlere patronluk yaparak ilim adamlarına ve yeni buluşlara destek verdi; kaynaklara göre bir tür yeni nakış işlemeciliği tekniği bile geliştirdiği söylenir. Kısacası II. Attalos, evlat sevgisiyle ün kazanmış “Philadelphos” lakaplı bir kral olarak kalıp barışçı politikalar izledi. Onun döneminde Pergamon’un altın çağı mimari geleneği sürdü; en büyük yenilikler arasında Attalia’nın kurulması ve kent içi yapılarda istikrar sayılabilir.", R.drawable.tarih13));
                modelArrayList.add(new PageModel("III. Attalos (M.Ö. 138–133)", "III. Attalos Philometor Euergetes, Bergama’nın son Attalid kralıdır (saltanat 138–133). İ. Eumenes’in oğlu olarak krallığa geçtiğinde henüz gençti ve saltanatı boyunca büyük siyasal veya mimari icraatlarda bulunmadı. Tarihçiler Attalos III’ün krallığa pek hevesi olmadığını, tıp, botanik ve tarımla ilgilendiğini kaydeder. Pergamon’da yeni tapınak veya anıt inşa ettirmedi; yönetim işlerini annesi ve vezirleriyle yürütmeye devam etti.", R.drawable.tarih14));
                modelArrayList.add(new PageModel("III. Attalos (M.Ö. 138–133)", "En önemli politik eylemi çocuk bırakmadan ölmesi ve krallığı Roma Cumhuriyeti’ne vasiyet etmesidir. 133’te varissiz ölümü üzerine Pergamon krallığını Roma’ya bıraktı; bu karar “kan dökülmesin” ve Roma’nın isteyeceğine göre barışçıl çözüm gerekçeleriyle açıklanmıştır. Attalos’un ölümünün ardından tahta hakkı olduğuna inanan Aristonikos (Eumenes II’nin iddia edilen oğlu) Eumenes III adıyla isyan başlattı. M.Ö. 129’da Roma konsülü M. Perperna’nın ordusu Aristonikos’u mağlup etti ve Pergamon’u Roma, Pontus ve Kapadokya arasında paylaştırdı; ana topraklar ise yeni Roma Asya eyaletine dönüştü. III. Attalos döneminde Pergamon’un Helenistik krallığı sona ermiş; kent Roma yönetimine geçmiştir. Attalos III’ün saltanatında, bilimsel merak ve annesine düşkünlük (soyadı “Philometor”, “Annesini seven”) ön plandaydı. Onun ilgi alanları, seleukos ve pergamon kültürünün zengin mirasının şekillenmesinde artık son katkılar olarak kayda geçmiştir.", R.drawable.tarih15));
                break;
        }

        adapter = new Adapter(this, modelArrayList);
        viewPager.setAdapter(adapter);
        viewPager.setPadding(70, 0, 70, 0);
    }
}
